repos:

- repo: https://github.com/psf/black
  rev: v23.7.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/isort
  rev: v5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=1500']