name: Code Formatting

on:
  push:
    branches-ignore: 
      - main
  pull_request:
    types: 
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    name: PR Formatter

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Format the code
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "."

      - name: Check-in updated code
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}